"""
From:
    https://github.com/HazyResearch/cartridges/blob/main/cartridges/synthesizers/self_study.py#L842-L949
"""

COT_INSTRUCTIONS = [
    "Explain your reasoning before providing your final response.",
    "First, walk through your reasoning process step by step. Then, clearly state your final answer.",
    "Begin by explaining how you approach the problem. Afterward, give your final response.",
    "Start with a detailed breakdown of your thought process. Conclude with a concise answer.",
    "Explain your logic as you work through the problem. When you're done, provide your conclusion.",
    "Think out loud as you reason through the question. End with a definitive answer.",
    "Work through the problem in detail, reasoning carefully. Then summarize your final decision.",
    "Describe each step you take to solve the problem. Finish by stating the final result.",
    "Provide a thorough explanation of how you arrive at your answer. Then state the answer clearly.",
    "Show your reasoning process from start to finish. Make sure to give your final answer at the end.",
    "Break the problem into logical steps and explain each one. Then give your final response.",
    "Write out your reasoning clearly and methodically. Conclude with your final conclusion.",
    "Reflect on the problem and describe your full reasoning. Then, say what your answer is.",
    "Think critically about the question and narrate your process. Then provide your final decision.",
    "Feel free to think it through out loud first, then just drop your answer at the end.",
    "Walk yourself through the problem—no rush. Once you're set, say what you'd go with.",
    "You can talk it out step by step. Just wrap up with whatever you think the answer is.",
    "Think it through however you like, and then let me know your final call.",
    "Start by working through the logic in your own way. When you're done, give the answer.",
    "Lay out your thinking as it comes to you. At the end, just say what you'd choose.",
    "Break it down how you want, no pressure. Then tell me what your final answer would be.",
    "Talk yourself through the reasoning part. When it feels right, give your answer.",
    "Explain it like you're figuring it out in real time, then land on your pick.",
    "Take a moment to think it through, and when you're ready, just say your answer.",
    "Work it out however makes sense to you. Then drop your answer when you're good.",
    "Go step by step, like you're thinking out loud. End with whatever answer you'd settle on.",
    "Walk through your reasoning step by step, and once it all clicks, share your answer.",
    "Take me through your thought process from start to finish, then tell me your conclusion.",
    "Think out loud as you piece it together. When you’re ready, just state your answer.",
    "Break down the problem in your own words, then wrap up with your choice.",
    "Talk through each part as you solve it, and then give your final answer.",
    "Map out your logic as you go, and once you’re confident, give your answer.",
    "Reason it out at your own pace, and when you’re set, let me know your answer.",
    "Feel free to puzzle it out stepwise. At the end, just say your final pick.",
    "Process the question however you like. Once you’ve worked it out, share your answer.",
    "Unpack the problem in detail, and when you’re ready, provide your answer.",
    "Work through the details in your own style, and then land on your answer.",
    "Think through the scenario, explaining as you go, and finish with your answer.",
    "Go through your reasoning openly, and then make your final call.",
    "Lay out your analysis clearly, and when you reach a conclusion, share it.",
    "Step through your logic in real time, and end with your decision.",
    "Explain your approach as you solve it, then just give your answer at the end.",
    "Go through the motions of solving it, and when you’re done, state your answer.",
    "Work the problem out in your own way, and when you’re ready, say your answer.",
    "Detail your thought process as it unfolds, then close with your answer.",
    "Take your time to reason through it, and when you’ve got it, give your answer.",
]
